// Item tooltip: hover preview (desktop) + touch-mode action sheet (mobile).
// The HTML is generated by formatItemTooltip(); binding to a DOM element is
// done via bindTooltip() (hover) or showTouchLootTooltip() (tap).
//
// Cross-module calls go through panelState.helpers:
//   - resolveEquipSlotForItem - to decide "Equip" vs "Use" action label
//   - resolveSellUnitPrice    - to show "Sell (N gp)" on the touch sheet

import { averageMagicWeaponHitPreview } from '../../mechanics/progression.js';
import { panelState } from './state.js';

let _activeTouchSlotCleanup = null;

export function hideItemTooltip() {
  const itemTooltip = document.getElementById('itemTooltip');
  if (!itemTooltip) return;
  itemTooltip.style.display = 'none';
  itemTooltip.textContent = '';
  itemTooltip.classList.remove('touch-mode');
  if (_activeTouchSlotCleanup) { _activeTouchSlotCleanup(); _activeTouchSlotCleanup = null; }
}

export function getFoodTimeSeconds(item) {
  const attrs = Array.isArray(item && item.attributes) ? item.attributes : [];
  const foodAttr = attrs.find((a) => (a && (a.name || '').toLowerCase() === 'food_time'));
  if (!foodAttr) return 0;
  const n = Number(foodAttr.value);
  return Number.isFinite(n) ? Math.max(0, Math.floor(n)) : 0;
}

export function escapeHtml(text) {
  return String(text == null ? '' : text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function formatItemTooltip(item) {
  if (!item) return '';
  const raw = item.raw && typeof item.raw === 'object' ? item.raw : {};
  const title = item.title || raw.title || 'Unknown Item';
  const cls = item.item_class || raw.item_class || 'Item';
  const type = item.item_type || raw.item_type || 'Unknown';
  const sellRaw = Number(raw.value_sell || 0);
  const buyRaw = Number(raw.value_buy || 0);
  const price = Math.max(0, sellRaw > 0 ? sellRaw : buyRaw);
  const weight = Number(raw.weight != null ? raw.weight : item.weight || 0);
  const safeTitle = escapeHtml(title);
  const safeType = escapeHtml(type);
  const safeWeight = Number.isFinite(weight) ? weight : 0;
  const isEquippable = Boolean(
    panelState.helpers.resolveEquipSlotForItem &&
    panelState.helpers.resolveEquipSlotForItem(item),
  );
  const isSameItem = (a, b) => {
    if (!a || !b) return false;
    if (a.id != null && b.id != null) return Number(a.id) === Number(b.id);
    return String(a.title || '').trim().toLowerCase() === String(b.title || '').trim().toLowerCase();
  };
  const isCurrentlyEquipped = Object.values(panelState.equippedSlots || {}).some((eq) => isSameItem(eq, item));
  const primaryAction = isCurrentlyEquipped ? 'Unequip' : (isEquippable ? 'Equip' : 'Use');
  const attrs = Array.isArray(item.attributes) ? item.attributes : [];
  const attrNum = (name) => {
    const row = attrs.find((a) => a && String(a.name || '').toLowerCase() === name);
    const n = Number(row && row.value);
    return Number.isFinite(n) ? n : null;
  };
  const attackStat = attrNum('attack');
  const defenseStat = attrNum('defense');
  const armorStat = attrNum('armor');
  const attrText = (name) => {
    const row = attrs.find((a) => a && String(a.name || '').toLowerCase() === String(name).toLowerCase());
    return row ? String(row.value || '').trim() : '';
  };
  const handsAttr = attrText('hands').toLowerCase();
  const handsLabel = handsAttr === 'two'
    ? 'Two-handed'
    : (handsAttr === 'one' ? 'One-handed' : null);
  const isWeaponClass = String(cls || '').toLowerCase() === 'weapons';
  const ttRow = (label, value) =>
    `<div class="tt-row"><span class="tt-label">${label}</span><span class="tt-value">${value}</span></div>`;
  const statLines = [];
  if (isEquippable) {
    if (attackStat != null) statLines.push(ttRow('Attack', attackStat));
    if (defenseStat != null) statLines.push(ttRow('Defense', defenseStat));
    if (armorStat != null) statLines.push(ttRow('Armor', armorStat));
    if (isWeaponClass && handsLabel) statLines.push(ttRow('Hands', handsLabel));
  }
  const typeLower = String(type || '').toLowerCase();
  if (typeLower === 'wands' || typeLower === 'rods') {
    const hud = (typeof window !== 'undefined' && window.__gameHud) ? window.__gameHud : { ml: 0, pl: 1 };
    const mlHud = Number(hud.ml) || 0;
    const plHud = Number(hud.pl) || 1;
    const rangeStr = attrText('range');
    const dmgType = attrText('damage_type');
    const dmgRange = attrText('damage_range');
    const manaCost = attrText('mana_cost');
    const levelReq = attrText('level');
    const vocation = attrText('vocation');
    const hands = attrText('hands');
    const magicBonus = attrText('magic');
    const previewAvg = averageMagicWeaponHitPreview(dmgRange, mlHud, plHud);
    statLines.push('<div class="tt-sep"></div>');
    statLines.push('<div class="tt-section">Magic Weapon</div>');
    if (rangeStr) statLines.push(ttRow('Range', `${escapeHtml(rangeStr)} tiles`));
    if (dmgType) statLines.push(ttRow('Damage type', escapeHtml(dmgType)));
    if (dmgRange) statLines.push(ttRow('Damage', escapeHtml(dmgRange)));
    if (previewAvg != null) statLines.push(ttRow(`Est. hit (ML ${mlHud})`, `~${previewAvg}`));
    if (manaCost) statLines.push(ttRow('Mana / shot', escapeHtml(manaCost)));
    if (levelReq) statLines.push(ttRow('Req. level', escapeHtml(levelReq)));
    if (vocation) statLines.push(ttRow('Vocation', escapeHtml(vocation)));
    if (hands) statLines.push(ttRow('Hands', escapeHtml(hands)));
    if (magicBonus) statLines.push(ttRow('Magic', escapeHtml(magicBonus)));
    const skipNames = new Set(['is_walkable', 'upgrade_classification', 'weapon_type', 'range', 'damage_type', 'damage_range', 'mana_cost', 'level', 'vocation', 'hands', 'magic']);
    const showExtra = attrs.filter((a) => a && a.name && !skipNames.has(String(a.name).toLowerCase())).slice(0, 8);
    if (showExtra.length > 0) {
      statLines.push('<div class="tt-sep"></div>');
      for (const a of showExtra) {
        statLines.push(ttRow(escapeHtml(String(a.name || '')), escapeHtml(String(a.value != null ? a.value : ''))));
      }
    }
  }
  if (typeLower === 'rings' || typeLower === 'amulets and necklaces') {
    const ACCESSORY_FRIENDLY = {
      'duration': 'Duration',
      'charges': 'Charges',
      'speed': 'Speed bonus',
      'regeneration': 'Regeneration',
      'magic': 'Magic level',
      'fist': 'Fist fighting',
      'sword': 'Sword fighting',
      'club': 'Club fighting',
      'axe': 'Axe fighting',
      'distance': 'Distance fighting',
      'shielding': 'Shielding',
      'physical%': 'Physical resist.',
      'fire%': 'Fire resist.',
      'earth%': 'Earth resist.',
      'energy%': 'Energy resist.',
      'ice%': 'Ice resist.',
      'death%': 'Death resist.',
      'holy%': 'Holy resist.',
    };
    const priorityOrder = ['duration', 'charges', 'speed', 'regeneration',
      'magic', 'fist', 'sword', 'club', 'axe', 'distance', 'shielding',
      'physical%', 'fire%', 'earth%', 'energy%', 'ice%', 'death%', 'holy%'];
    const skipAccessory = new Set(['is_walkable', 'upgrade_classification', 'weapon_type']);
    const shown = new Set();
    if (attrs.length > 0) {
      statLines.push('<div class="tt-sep"></div>');
      for (const pKey of priorityOrder) {
        const row = attrs.find((a) => a && String(a.name || '').toLowerCase() === pKey);
        if (!row) continue;
        shown.add(pKey);
        statLines.push(ttRow(escapeHtml(ACCESSORY_FRIENDLY[pKey] || pKey), escapeHtml(String(row.value != null ? row.value : ''))));
      }
      for (const a of attrs) {
        const nm = String(a.name || '').toLowerCase();
        if (skipAccessory.has(nm) || shown.has(nm)) continue;
        statLines.push(ttRow(escapeHtml(ACCESSORY_FRIENDLY[nm] || a.name), escapeHtml(String(a.value != null ? a.value : ''))));
      }
    }
  }
  const bodyRows = [
    `<div class="tt-row"><span class="tt-label">Type</span><span class="tt-value">${safeType}</span></div>`,
    price > 0 ? `<div class="tt-row"><span class="tt-label">Price</span><span class="tt-value tt-gold">${price} gp</span></div>` : '',
    safeWeight > 0 ? `<div class="tt-row"><span class="tt-label">Weight</span><span class="tt-value">${safeWeight} oz</span></div>` : '',
    ...statLines,
  ].filter(Boolean).join('');
  const actionRow = `<div class="tt-actions"><span class="tt-act-icon">⟵</span> ${primaryAction}&ensp;<span class="tt-act-sep">|</span>&ensp;<span class="tt-act-icon">⟶</span> Sell</div>`;
  return `<div class="tt-header"><div class="tt-title">${safeTitle}</div></div><div class="tt-body">${bodyRows}</div><div class="tt-footer">${actionRow}</div>`;
}

export function bindTooltip(el, item) {
  const itemTooltip = document.getElementById('itemTooltip');
  if (!el || !itemTooltip || !item) return;
  const text = formatItemTooltip(item);
  if (!text) return;
  const placeNearElement = () => {
    const rect = el.getBoundingClientRect();
    const tipW = itemTooltip.offsetWidth || 210;
    const tipH = itemTooltip.offsetHeight || 80;
    // Always LEFT of the item, clamped to viewport
    let x = rect.left - tipW - 4;
    if (x < 4) x = rect.right + 4;
    if (x + tipW > window.innerWidth - 4) x = 4;
    // Vertically center the tooltip on the item cell
    let y = rect.top + (rect.height / 2) - (tipH / 2);
    if (y + tipH > window.innerHeight - 6) y = Math.max(4, window.innerHeight - tipH - 6);
    if (y < 4) y = 4;
    itemTooltip.style.left = `${Math.floor(x)}px`;
    itemTooltip.style.top = `${Math.floor(y)}px`;
  };
  const show = () => {
    itemTooltip.innerHTML = text;
    itemTooltip.classList.remove('touch-mode');
    itemTooltip.style.display = 'block';
    void itemTooltip.offsetWidth;
    placeNearElement();
  };
  const move = () => { placeNearElement(); };
  const hide = () => { hideItemTooltip(); };
  el.addEventListener('mouseenter', show);
  el.addEventListener('mousemove', move);
  el.addEventListener('mouseleave', hide);
}

/** Touch-friendly tooltip with action buttons for loot items. */
export function showTouchLootTooltip(el, item, _lootIndex) {
  // _lootIndex is passed by callers but unused here; actions dispatch via simulated events on `el`.
  const itemTooltip = document.getElementById('itemTooltip');
  if (!el || !itemTooltip || !item) return;
  if (_activeTouchSlotCleanup) { _activeTouchSlotCleanup(); _activeTouchSlotCleanup = null; }
  hideItemTooltip();

  const text = formatItemTooltip(item);
  if (!text) return;

  const typeLower = (item.item_type || '').toLowerCase();
  let useLabel = 'Equip';
  if (typeLower === 'food') useLabel = 'Eat';
  else if (typeLower === 'liquids') useLabel = 'Drink';
  else if (typeLower === 'tools') useLabel = 'Use';

  const sellUnit = panelState.helpers.resolveSellUnitPrice
    ? panelState.helpers.resolveSellUnitPrice(item)
    : 0;
  const sellPrice = sellUnit * Math.max(1, Number(item.count || 1));

  itemTooltip.innerHTML = text
    + `<div class="tt-touch-actions">`
    + `<button class="tt-touch-btn tt-touch-btn-use" data-action="use">${useLabel}</button>`
    + `<button class="tt-touch-btn tt-touch-btn-sell" data-action="sell">Sell (${Math.floor(sellPrice)} gp)</button>`
    + `</div>`;
  itemTooltip.classList.add('touch-mode');
  itemTooltip.style.display = 'block';
  void itemTooltip.offsetWidth;

  const rect = el.getBoundingClientRect();
  const tipW = itemTooltip.offsetWidth || 210;
  const tipH = itemTooltip.offsetHeight || 80;
  let x = rect.left - tipW - 4;
  if (x < 4) x = rect.right + 4;
  if (x + tipW > window.innerWidth - 4) x = Math.max(4, (window.innerWidth - tipW) / 2);
  let y = rect.top + (rect.height / 2) - (tipH / 2);
  if (y + tipH > window.innerHeight - 6) y = Math.max(4, window.innerHeight - tipH - 6);
  if (y < 4) y = 4;
  itemTooltip.style.left = `${Math.floor(x)}px`;
  itemTooltip.style.top = `${Math.floor(y)}px`;

  const onBtn = (ev) => {
    ev.preventDefault();
    ev.stopPropagation();
    const action = ev.target.dataset.action;
    if (action === 'use') {
      // Simulate left-click on this slot (panel's mousedown handler does the work)
      el.dispatchEvent(new MouseEvent('mousedown', { button: 0, bubbles: true }));
    } else if (action === 'sell') {
      el.dispatchEvent(new Event('contextmenu', { bubbles: true }));
    }
    hideItemTooltip();
  };

  const useBtn  = itemTooltip.querySelector('[data-action="use"]');
  const sellBtn = itemTooltip.querySelector('[data-action="sell"]');
  if (useBtn)  useBtn.addEventListener('click', onBtn);
  if (sellBtn) sellBtn.addEventListener('click', onBtn);

  const dismissHandler = (ev) => {
    if (itemTooltip.contains(ev.target)) return;
    if (el.contains(ev.target)) return;
    hideItemTooltip();
    document.removeEventListener('touchstart', dismissHandler, true);
  };
  setTimeout(() => { document.addEventListener('touchstart', dismissHandler, true); }, 50);

  _activeTouchSlotCleanup = () => {
    document.removeEventListener('touchstart', dismissHandler, true);
  };
}
