export const CREATURE_ABILITY_PATTERN_BY_NAME = {
  'self-healing': { kind: 'none' },
  'self healing': { kind: 'none' },
  'frequent self-healing': { kind: 'none' },
  melee: { kind: 'player_cell' },
  'physical damage': { kind: 'player_cell' },
  'area attack': { kind: 'nova_creature', radius: 1 },
  'earth strike': { kind: 'player_cell' },
  'death strike': { kind: 'player_cell' },
  'energy strike': { kind: 'player_cell' },
  'ice strike': { kind: 'player_cell' },
  'fire strike': { kind: 'player_cell' },
  'flame strike': { kind: 'player_cell' },
  'poison strike': { kind: 'player_cell' },
  'life drain strike': { kind: 'player_cell' },
  'death hit': { kind: 'player_cell' },
  'poison hit': { kind: 'player_cell' },
  'fire beam': { kind: 'line_to_player', maxLen: 5 },
  'death beam': { kind: 'line_to_player', maxLen: 5 },
  'energy beam': { kind: 'line_to_player', maxLen: 5 },
  'poison beam': { kind: 'line_to_player', maxLen: 5 },
  'ice beam': { kind: 'line_to_player', maxLen: 5 },
  'holy beam': { kind: 'line_to_player', maxLen: 5 },
  'life drain beam': { kind: 'line_to_player', maxLen: 5 },
  'great energy beam': { kind: 'line_to_player', maxLen: 8 },
  'fire wave': { kind: 'cone_to_player', depth: 3 },
  'poison wave': { kind: 'cone_to_player', depth: 3 },
  'earth wave': { kind: 'cone_to_player', depth: 3 },
  'ice wave': { kind: 'cone_to_player', depth: 3 },
  'energy wave': { kind: 'cone_to_player', depth: 3 },
  'death wave': { kind: 'cone_to_player', depth: 3 },
  'life drain wave': { kind: 'cone_to_player', depth: 3 },
  'explosion wave': { kind: 'cone_to_player', depth: 3 },
  'smoke wave': { kind: 'cone_to_player', depth: 3 },
  'sudden death': { kind: 'player_cell' },
  'fire missile': { kind: 'player_cell' },
  'energy missile': { kind: 'player_cell' },
  'earth missile': { kind: 'player_cell' },
  'ice missile': { kind: 'player_cell' },
  'death missile': { kind: 'player_cell' },
  'heavy magic missile': { kind: 'player_cell' },
  fireball: { kind: 'player_cell' },
  'fire ball': { kind: 'player_cell' },
  'poison ball': { kind: 'player_cell' },
  'death ball': { kind: 'player_cell' },
  'energy ball': { kind: 'player_cell' },
  'earth ball': { kind: 'player_cell' },
  'blood ball': { kind: 'player_cell' },
  'holy ball': { kind: 'player_cell' },
  'paralyze ball': { kind: 'player_cell' },
  stalagmite: { kind: 'player_cell' },
  'great fireball': { kind: 'nova_at_player', radius: 1 },
  'fire bomb': { kind: 'nova_at_player', radius: 1 },
  'poison bomb': { kind: 'nova_at_player', radius: 1 },
  'death bomb': { kind: 'nova_at_player', radius: 1 },
  'fire explosion': { kind: 'nova_at_player', radius: 1 },
  'death explosion': { kind: 'nova_at_player', radius: 1 },
  'poison explosion': { kind: 'nova_at_player', radius: 1 },
  explosion: { kind: 'plus_on_player' },
  berserk: { kind: 'nova_creature', radius: 1 },
  'life drain berserk': { kind: 'nova_creature', radius: 1 },
  'poison berserk': { kind: 'nova_creature', radius: 1 },
  'energy berserk': { kind: 'nova_creature', radius: 1 },
  'whirlwind throw': { kind: 'line_to_player', maxLen: 4 },
  'throws spears': { kind: 'player_cell' },
  'poison spit': { kind: 'player_cell' },
  sparkles: { kind: 'nova_creature', radius: 1 },
  'cloud explosion': { kind: 'nova_at_player', radius: 1 },
  'red sparkles bomb': { kind: 'nova_at_player', radius: 1 },
  'green sparkles bomb': { kind: 'nova_at_player', radius: 1 },
  envenom: { kind: 'player_cell' },
  paralyze: { kind: 'player_cell' },
  paralysis: { kind: 'player_cell' },
  'distance paralyze': { kind: 'player_cell' },
  'mana drain exori': { kind: 'nova_creature', radius: 1 },
  'mana drain': { kind: 'player_cell' },
  'life drain': { kind: 'player_cell' },
  'distance life drain': { kind: 'player_cell' },
  'biting cold': { kind: 'cone_to_player', depth: 3 },
};

export function inferCreatureAbilityPattern(ability) {
  const name = String((ability && ability.name) || '').toLowerCase().trim();
  if (CREATURE_ABILITY_PATTERN_BY_NAME[name]) return { ...CREATURE_ABILITY_PATTERN_BY_NAME[name] };
  if (name === 'none' || name.includes('probably other') || name.includes('and more') || name.includes('invisib')) return { kind: 'none' };
  if (name.includes('bomb') || name.includes('great fireball')) return { kind: 'nova_at_player', radius: 1 };
  if (name.includes('beam')) return { kind: 'line_to_player', maxLen: name.includes('great') ? 8 : 5 };
  if (name.includes('wave')) return { kind: 'cone_to_player', depth: 3 };
  if (name.includes('berserk')) return { kind: 'nova_creature', radius: 1 };
  if (name.includes('explosion')) return name.includes('wave') ? { kind: 'cone_to_player', depth: 3 } : { kind: 'nova_at_player', radius: 1 };
  if (name.includes('missile') || name.includes('strike') || name.includes('ball') || name.includes('spit') || name.includes('stalagmite') || name.includes('throw') || name.includes('hit') || name.includes('harvest')) return { kind: 'player_cell' };
  if (name.includes('area')) return { kind: 'nova_creature', radius: 1 };
  return { kind: 'player_cell' };
}
